# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-25 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='pic_url',
            field=models.CharField(default='Fill', max_length=1000),
            preserve_default=False,
        ),
    ]
