# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180419_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
