# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-15 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180503_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug will be generated automatically from the title of the post'),
        ),
    ]
